env:
  commonjs: true
  es6: true
  node: true
extends: google
parserOptions:
  ecmaVersion: 2018
rules:
  max-len:
    - error
    - code: 300
  require-jsdoc:
    - off
  linebreak-style: 0
  semi: 0
  space-before-function-paren: 0
  max-lines-per-function: 0
  indent: off
  padded-blocks: off
  comma-dangle: off
